layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: false
    projects:
     - curioustushar.github.io

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  stackoverflow: 2224265
  linkedin: curioustushar
  twitter: curioustushar
  hackerrank: curioustushar
  # instagram: your_username
  # keybase: your_username
  # mastodon: your_username
  # medium: your_username
  # telegram: your_username
  # unsplash: your_username
  # vk: your_username
  website: http://curioustushar.com
  # youtube: your_username

topics:
  - name: JavaScript
    web_url: https://github.com/topics/js
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/javascript/javascript.png

  - name: Node.js
    web_url: https://github.com/topics/nodejs
    image_url: https://raw.githubusercontent.com/github/explore/fd96fceccf8c42c99cbe29cf0f8dcc4736fcb85a/topics/nodejs/nodejs.png

  - name: MongoDB
    web_url: https://github.com/topics/mongodb
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/mongodb/mongodb.png

  - name: Elasticsearch
    web_url: https://github.com/topics/elasticsearch
    image_url: https://avatars0.githubusercontent.com/u/6764390?s=200&v=4

  - name: Linux
    web_url: https://github.com/topics/linux
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/linux/linux.png

  - name: Ubuntu
    web_url: https://github.com/topics/ubuntu
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/ubuntu/ubuntu.png

  - name: Docker
    web_url: https://github.com/topics/docker
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/docker/docker.png
